[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Correct redirects for Next.js (single page app routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production
[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://sam24fit.netlify.app"
  NEXT_PUBLIC_SUPABASE_URL = "https://noidkepohqhgdalkvzze.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vaWRrZXBvaHFoZ2RhbGt2enplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTE4MTYsImV4cCI6MjA2OTg4NzgxNn0.sPoMpbSuSFgwvs_HbqBMhOWLU1PnM4EMm0psMQxhLLM"
  NODE_ENV = "production"

# Environment variables for deploy previews
[context.deploy-preview.environment]
  NEXT_PUBLIC_SITE_URL = "https://deploy-preview-$DEPLOY_ID--sam24fit.netlify.app"
  NEXT_PUBLIC_SUPABASE_URL = "https://noidkepohqhgdalkvzze.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vaWRrZXBvaHFoZ2RhbGt2enplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTE4MTYsImV4cCI6MjA2OTg4NzgxNn0.sPoMpbSuSFgwvs_HbqBMhOWLU1PnM4EMm0psMQxhLLM"
  NODE_ENV = "production"

# Environment variables for branch deploys
[context.branch-deploy.environment]
  NEXT_PUBLIC_SITE_URL = "https://$BRANCH--sam24fit.netlify.app"
  NEXT_PUBLIC_SUPABASE_URL = "https://noidkepohqhgdalkvzze.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vaWRrZXBvaHFoZ2RhbGt2enplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTE4MTYsImV4cCI6MjA2OTg4NzgxNn0.sPoMpbSuSFgwvs_HbqBMhOWLU1PnM4EMm0psMQxhLLM"
  NODE_ENV = "production"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"